### ISSUE TITLE
Outdated info to add table from existing connections in AS Tabular

### ISSUE THREAD

**Issue by kthejoker** [MicrosoftDocs/bi-shared-docs#1]
https://docs.microsoft.com/en-us/analysis-services/tabular-models/add-a-table-ssas-tabular

says hit the Existing Connections button from the Model menu in SSDT.

But that's not there anymore; to add tables from existing connections you right click on the data source in the Model Explorer and hit "Add New Tables"

**Comment by Minewiskan** [comment]
@kthejoker - Thanks for your comment. This article has now been updated. Unfortunately, documentation is not always updated right away when there are changes in the tools.
