### ISSUE TITLE
SSAS Calculation Group Sideways Recursion example has invalid DAX

### ISSUE THREAD

**Issue by alwortman** [MicrosoftDocs/bi-shared-docs#16]
[https://github.com/MicrosoftDocs/bi-shared-docs/blob/master/docs/analysis-services/tabular-models/calculation-groups.md#sideways-recursion](url)

DAX example must either provide argument 3 for the DIVIDE function, or omit it.

**Comment by Minewiskan** [comment]
https://docs.microsoft.com/en-us/analysis-services/tabular-models/calculation-groups?view=asallproducts-allversions#sideways-recursion
