### ISSUE TITLE
MDX in Tabular?

### ISSUE THREAD

**Issue by matepolsps** [MicrosoftDocs/bi-shared-docs#19]
Dear Author - when talking about MDX limitations in the context of a Tabular model, could you make it clear that you are talking about MDX queries executed against the tabular database from outside. Or if these are some kind of MDX expressions in the tabular data structure (which I thought was not possible) what are they? Thank you!

**Comment by Minewiskan** [comment]
@matepolsps - Could you be more specific about which articles in the existing documentation you are referring to?

**Comment by Minewiskan** [comment]
Closing due to no response.
