### ISSUE TITLE
Online Attach - DbStorageLocation issue

### ISSUE THREAD

**Issue by PowerDAX** [MicrosoftDocs/bi-shared-docs#20]
Attempting to perform an online attach (https://docs.microsoft.com/en-us/analysis-services/what-s-new-in-sql-server-analysis-services?view=asallproducts-allversions#sql-server-2019-analysis-services) in SSAS 2019.

the attach command

<Attach xmlns="http://schemas.microsoft.com/analysisservices/2003/engine">
  <Folder>F:\data\EnterpriseModelCopy.0.db\</Folder>
  <ReadWriteMode xmlns="http://schemas.microsoft.com/analysisservices/2008/engine/100">ReadOnly</ReadWriteMode>
  <Password>P@ssW0rD!</Password>
  <AllowOverwrite>true</AllowOverwrite>
</Attach>

provides an error:

Executing the query ...
Attach with AllowOverwrite=true over existing database is supported only for databases with DBStorageLocation property specified. The database 'EnterpriseModel' that is being attached has no DBStorageLocation specified.
Run complete

if we attempt to run the attach command w/ DBStorageLocation specified:

<Attach xmlns="http://schemas.microsoft.com/analysisservices/2003/engine">
                <Folder>F:\data\EnterpriseModelCopy.0.db\</Folder>
                <ReadWriteMode xmlns="http://schemas.microsoft.com/analysisservices/2008/engine/100">ReadOnly</ReadWriteMode>
                <Password>P@ssW0rD!</Password>
                <AllowOverwrite>true</AllowOverwrite>
                <DBStorageLocation>F:\data\EnterpriseModel.0.db\</DBStorageLocation>
</Attach>

we receive the error message:

Executing the query ...
The DBStorageLocation element at line 12, column 20 (namespace http://schemas.microsoft.com/analysisservices/2003/engine) cannot appear under Envelope/Body/Execute/Command/Attach.
Run complete

We also attempted to 
1. backup/restore on the processing server to set the dbstoragelocation
2. detach the solution w/ dbstoragelocation set
3. copy the solution over to the query server
4. attach as the query server solution
5. run the online attach and received the same error

**Comment by Minewiskan** [comment]
@PowerDAX - Please submit a support request or post your question on the forums. This is outside the scope of GitIssues for documentation.
