### ISSUE TITLE
Tabular Partition page doesn't match AdventureWorksDW2019 database

### ISSUE THREAD

**Issue by tonywr71** [MicrosoftDocs/bi-shared-docs#29]
In tabular tutorial, the partitioning doesn't match the data in the AdventureWorksDW2019 database. As a result, no rows are returned when I process the partitions. (Unless, of course, I've missed something and am doing something wrong!)

[bi-shared-docs/docs/analysis-services/tutorial-tabular-1400/as-lesson-10-create-partitions.md](bi-shared-docs/docs/analysis-services/tutorial-tabular-1400/as-lesson-10-create-partitions.md)

I am using the AdventureWorksDW2019 database found [here](https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver15&tabs=ssms)

It wouldn't surprise me if the data was updated after this was published.

**Comment by tonywr71** [comment]
Oh, I've added a decade to all the values and run Process Table and it appears to have loaded everything. But it is an error in the docos I think. Adventure Works has been around a long time and I guess someone attempted to modernise the dates stored in the table.

**Comment by Minewiskan** [comment]
@tonywr71 - We're aware of the discrepancies. The tutorial guidance [prerequisites ](https://docs.microsoft.com/en-us/analysis-services/tutorial-tabular-1400/as-adventure-works-tutorial?view=asallproducts-allversions#prerequisites) describe using the sample AdventureWorksDW in Azure Synapse as a data source. That sample version for Synapse is really old (and broken). The Synapse team is working to get that updated to a newer version of the AdventureWorksDW sample DB. Earlier versions of this tutorial did guide users through installing a local version of AdvWorksDW on a local SQLDW instance, but as most users are now deploying to cloud instances of Azure AS, we didn't want to drag tutorial users through setting up data gateway to access the local SQLDW instance. For the time-being, we're kind of stuck with an old sample data source. Thankfully users such as yourself are adept at getting around that.
