### ISSUE TITLE
Missing associated measure group option

### ISSUE THREAD

**Issue by TurchinAlexander** [MicrosoftDocs/bi-shared-docs#32]
Hello.
It seems that in [Defining and browsing KPI page](https://github.com/MicrosoftDocs/bi-shared-docs/blob/master/docs/analysis-services/multidimensional-tutorial/lesson-7-1-defining-and-browsing-kpis.md) associated measure group option select is missing.
![image](https://user-images.githubusercontent.com/37373636/120545578-8162b400-c3f7-11eb-86bb-01d09c19fe3f.png)

I expect that the tutorial will say what option I should select. Like in first example.
![image](https://user-images.githubusercontent.com/37373636/120545817-c850a980-c3f7-11eb-9353-1e2b20d949ea.png)

**Comment by Minewiskan** [comment]
Unfortunately this is not something we can repo in reasonable amount of time. Unless there is a breaking issue with a request for a correction from support, MD docs are no longer being updated.
