### ISSUE TITLE
Libraries links are broken. 

### ISSUE THREAD

**Issue by true-pigmaster** [MicrosoftDocs/bi-shared-docs#37]
The links for MSOLAP libs are showing 404 not found. 
https://download.microsoft.com/download/3/8/B/38B8BD8C-E6AB-4B9F-AB1E-03C59A477C48/1033/x86_15.0.2000.802_SQL_AS_OLEDB.msi
![msolap](https://user-images.githubusercontent.com/1555962/129925283-78565829-f214-4939-8163-a50a5b2d5a2b.PNG)

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@true-pigmaster  Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

@Minewiskan Could you please update the broken links in the above document?

**Comment by Minewiskan** [comment]
@true-pigmaster, @CHEEKATLAPRADEEP-MSFT 
The client library downloads were removed by engineering. Currently there is nothing for the links to point to. Engineering is working on replacement client libraries. When available on Downloads, the links will function correctly.

**Comment by true-pigmaster** [comment]
Awesome, Thank you for confirmation.
