### ISSUE TITLE
Standard tier should be put explicitly in the prerequisites for analysis services in the tutorial

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/bi-shared-docs#46]
In https://github.com/MicrosoftDocs/bi-shared-docs/blob/6b4fba5ce278b1fdc801cee554e7673009cba21d/docs/analysis-services/tutorial-tabular-1400/as-adventure-works-tutorial.md it is not explained that the Standard tier of Azure Analysis Services should be used because lesson 10 creates multiple partitions.
If people create a resource with the Basic tier they will need to delete and reprovision their Analysis Services resource.

**Comment by Minewiskan** [comment]
Agreed. Thanks for pointing this out. The prerequisites to complete lesson 13 have been updated to an Azure AS server at the Developer or Standard tier.
