### ISSUE TITLE
Tabular Database - 1130 and higher is not alllowing reserved characters

### ISSUE THREAD

**Issue by kuwakino** [MicrosoftDocs/bi-shared-docs#53]
https://github.com/MicrosoftDocs/bi-shared-docs/blob/01727e758dad05ac7e478f58f72461dbd3512582/docs/analysis-services/multidimensional-models/olap-physical/object-naming-rules-analysis-services.md?plain=1#L81

Tried this code (based on [here](https://learn.microsoft.com/en-us/analysis-services/tom/create-and-deploy-an-empty-database-analysis-services-amo-tom?view=asallproducts-allversions)):
```
using (Server server = new()) {
      server.Connect(connectionString);

      string newDatabaseName = "Tabular - [New Database]";

      Database blankDatabase = new() {
          Name = newDatabaseName,
          ID = newDatabaseName,
          CompatibilityLevel = 1500, //1130 and higher
          StorageEngineUsed = StorageEngineUsed.TabularMetadata,
          ModelType = ModelType.Tabular //Databases can have a ModelType of default. Default is equivalent to multidimensional, and thus does not support the use of reserved characters in column names.
      };

      server.Databases.Add(blankDatabase);
      blankDatabase.Update(UpdateOptions.ExpandFull);
  }
```
getting the error that reserved characters are not allowed:
> fail: Function.HandleProcessStreamCreateModelAsync[3] Executed 'ProcessStreamCreateModelJobHandler.HandleProcessStreamCreateModelAsync' (Failed, Id=b6f4580e-ea83-4b38-96e3-bc1514b6a3bf, Duration=27000ms) Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: ProcessStreamCreateModelJobHandler.HandleProcessStreamCreateModelAsync  ---> System.InvalidOperationException: The 'Name' property cannot contain any of the following characters: . , ; ' ` : / \ * | ? " & % $ ! + = ( ) [ ] { } < >    at Microsoft.AnalysisServices.NamedComponentCollection.ValidateForAddOrInsert(NamedComponent obj)    at Microsoft.AnalysisServices.NamedComponentCollection.Add(ModelComponent item)    at [...]

> fail: Host.Results[0] Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: ProcessStreamCreateModelJobHandler.HandleProcessStreamCreateModelAsync  ---> System.InvalidOperationException: The 'Name' property cannot contain any of the following characters: . , ; ' ` : / \ * | ? " & % $ ! + = ( ) [ ] { } < >    at Microsoft.AnalysisServices.NamedComponentCollection.ValidateForAddOrInsert(NamedComponent obj)    at Microsoft.AnalysisServices.NamedComponentCollection.Add(ModelComponent item) at [...]

**Comment by Minewiskan** [comment]
@kuwakino - Are you trying to create a tabular database or a multidimensional
database? The article you referenced is for multidimensional, but your code is for tabular. There is no 1500 compat level for multidimensional.

**Comment by kuwakino** [comment]
Yes, it's tabular database.

Ok. Thanks!
