### ISSUE TITLE
No documentation on Feature \ ParallelSourceQueries for Azure Analysis Services

### ISSUE THREAD

**Issue by TwoPatient** [MicrosoftDocs/bi-shared-docs#60]
Currently there is no documentation on Feature \ ParallelSourceQueries

https://github.com/MicrosoftDocs/bi-shared-docs/blob/main/docs/analysis-services/server-properties/feature-properties.md

![image](https://user-images.githubusercontent.com/1675480/208657619-79e8f2fb-82b8-4edc-ae4a-abeff2a49093.png)

**Comment by Minewiskan** [comment]
@TwoPatient - This property\feature flag is not yet enabled in any AS environment. When enabled, we'll get a definition in the doc, though it may be a month or two after.
