### ISSUE TITLE
Updated Links 

### ISSUE THREAD

**Issue by AshishKumarMehta** [MicrosoftDocs/bi-shared-docs#9]
Links are Wrong. Correct links are mentioned below for Article: https://docs.microsoft.com/en-us/analysis-services/multidimensional-models/backup-and-restore-of-analysis-services-databases

First Change:
How to Backup an Analysis Services Database (TechMantra) Link has changed from https://www.mytechmantra.com/LearnSQLServer/Backup_an_Analysis_Services_Database.html to https://www.mytechmantra.com/sql-server-analysis-services/how-to-backup-analysis-services-database-in-sql-server-using-sql-server-management-studio/

Second Change: Step by Step Article is on MyTechMantra.com and not on TechMantra

Third Change: Link has changed for Automate Backup of an Analysis Services Database from https://www.mytechmantra.com/LearnSQLServer/Automate_Backup_of_Analysis_Services_Database.html to https://www.mytechmantra.com/sql-server-analysis-services/how-to-automate-backup-of-analysis-services-database-using-sql-server-agent-job/

**Comment by Minewiskan** [comment]
@AshishKumarMehta - Thank you for pointing this out. This has been updated.
